# Generated by Django 3.2.4 on 2021-06-08 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='категория колледжа')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название города')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название страны')),
                ('code', models.SmallIntegerField(default='+', verbose_name='Код страны')),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='название')),
                ('street', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(choices=[('NAT', 'National'), ('PRV', 'PRIVATE')], default='NAT', max_length=3)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_api_app.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='college_api_app.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='college_api_app.country')),
            ],
        ),
    ]
